### ISSUE TITLE
这些问题怎么解决啊

### ISSUE THREAD

**Issue by yuzhendong** [452MJ/C9MJ#10]
Error:(39, 13) Failed to resolve: com.jakewharton:butterknife:8.5.1
<a href="openFile:C:/Users/Administrator/Desktop/C9MJ-master/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:(75, 18) Failed to resolve: com.squareup.leakcanary:leakcanary-android:1.5
<a href="openFile:C:/Users/Administrator/Desktop/C9MJ-master/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by 452MJ** [comment]
VPN

**Comment by 452MJ** [comment]
你设置的是android sdk下载的镜像，并不能连接到jcenter与maven的托管库

**Comment by yuzhendong** [comment]
应该怎样设置呢

**Comment by 452MJ** [comment]
下载个软件直接开个VPN就可以了，AS不用设置

**Comment by yuzhendong** [comment]
代理的方式怎样设置呢

**Comment by 452MJ** [comment]
AS不需要设置代理，重置清空就行。

**Comment by yuzhendong** [comment]
你也是使用VPN代理软件的吗？有推荐的免费软件吗

**Comment by yuzhendong** [comment]
我安装了VPN代理软件 ，还是编译不成功啊

**Comment by 452MJ** [comment]
这...我也没办法了，找不到库的原因只有网络原因，我这边一切正常啊

**Comment by 452MJ** [comment]
#5 把代理注释掉
