### ISSUE TITLE
请问你怎么把流的截图当做封面的？

### ISSUE THREAD

**Issue by fzxm** [452MJ/C9MJ#11]
想学习一下

**Comment by 452MJ** [comment]
API返回的，不是自己截图 ，所有直播的封面都是后台处理返回个url。

**Comment by fzxm** [comment]
不是可以通过FFmpegMediaMetadataRetriever获取当前帧?可是我用这个获取到当封面直接内存块溢出了 很卡,后台返回的好处是啥 ,后台怎么获取?

**Comment by 452MJ** [comment]
1.那么多直播间，APP不可能每个房间都访问一遍吧，而且封面不是实时的。
2.推流的数据都要经过后台处理分发的，这样服务器周期截取其中一帧来作封面是很方便的

还是不清楚的话，你开个抓包软件看下数据结构就清楚了

**Comment by fzxm** [comment]
恩恩 谢谢了
