### ISSUE TITLE
斗鱼的视频地址失效了

### ISSUE THREAD

**Issue by Mr-wangyong** [452MJ/C9MJ#12]
项目很不错,想问问我是否能参与一起开发,

**Comment by 452MJ** [comment]
播斗鱼会报403，应该是要通过一个验证才能播放了，所以斗鱼那边我不知道具体验证方式。

项目的话，我也不知道能加什么需求了，你觉得不错的话可以自己fork下来去添加修改吧。
现在在学习React Native，这个直播APP估计也很少碰了。
