### ISSUE TITLE
内存泄漏比较多啊，

### ISSUE THREAD

**Issue by livelitoday** [452MJ/C9MJ#14]
请问这个leak的检测工具怎么绑定到这个app上的，就是怎么就能够检测C9MJapp的内存泄漏？

**Comment by 452MJ** [comment]
@livelitoday [LeakCanary](https://github.com/square/leakcanary)用这个就可以检测出来了。目前主要发现的泄露主要发生在播放页，且大多由于RxJava本身库的特性所引发泄露，如果有需要的话可以自己集成[RxLifecycle](https://github.com/trello/RxLifecycle)。
