### ISSUE TITLE
想知道如何抓取到直播流的？

### ISSUE THREAD

**Issue by littleBoy-swag** [452MJ/C9MJ#15]
如何实现可以看直播 的？平台不是加密了吗

**Comment by 452MJ** [comment]
我用的是max+ APP的接口

**Comment by littleBoy-swag** [comment]
能分享一下吗，给个地址啥的

**Comment by 452MJ** [comment]
http://api.maxjia.com

**Comment by 452MJ** [comment]
[具体的API](https://github.com/452MJ/C9MJ/blob/master/app/src/main/java/com/c9mj/platform/live/api/LiveAPI.java)

**Comment by littleBoy-swag** [comment]
多谢帮助，祝升职加薪，新年快乐
