### ISSUE TITLE
问一下,这个怎么解决?

### ISSUE THREAD

**Issue by AnkiDn** [452MJ/C9MJ#8]
Error:Could not GET 'https://jcenter.bintray.com/me/tatarka/gradle-retrolambda/3.4.0/gradle-retrolambda-3.4.0.pom'.

**Comment by 452MJ** [comment]
https://github.com/evant/gradle-retrolambda
你看下这个lambda插件的配置吧，之前是3.4.0版本，现在是3.6.0版本，只是用来兼容java8的特性而已。去掉的话不影响运行
